### ISSUE TITLE
BubbleSortV2应该不是冒泡排序了吧

### ISSUE THREAD

**Issue by zdpdp** [m9rco/algorithm-php#20]
function BubbleSortV2(array $container)
{
    $len = count($container);
    // 也可以用foreach
    for ($i = 0; $i < $len; $i++) {
        for ($j = $i + 1; $j < $len; $j++) {
            if ($container[$i] > $container[$j]) {
                list($container[$i], $container[$j]) = array($container[$j], $container[$i]);
            }
        }
    }

    return $container;
}

这样不是稳定排序了

**Comment by m9rco** [comment]
稳定排序？ 其实感觉用函数就不算算法了，但是我总觉得PHP其实也可以这样做

**Comment by awesee** [comment]
这个主要看思路分析：“就是像冒泡一样，每次从数组当中 冒一个最大的数出来。 ”，关键点在于for循环而不是list方法。很显然用sort更快，更方便，但它不符合要求。

**Comment by openset** [comment]
还有就是这是稳定排序。

**Comment by awesee** [comment]
仔细研究了一下，这个方法是不好。只是代码看起来少一点。
