### ISSUE TITLE
建议也加点优化算法，例如冒泡排序有很多优化方案

### ISSUE THREAD

**Issue by 1018ji** [m9rco/algorithm-php#21]
例如：以下URL中写的[ 冒泡排序及两种优化方式](http://blog.csdn.net/xufeng0991/article/details/47844327)

供别人参考

**Comment by awesee** [comment]
这个也就是练习练习思维用的，实际开发用不到这些，这些方法效率都很低。

**Comment by m9rco** [comment]
@1018ji 你可以提交上来呀
