### ISSUE TITLE
求帮助~ 给出一个处理方案

### ISSUE THREAD

**Issue by phpstudyone** [m9rco/algorithm-php#28]
由于安全方面限制,要求我们不能保存用户的信用卡信息,包括信用卡过期时间.
但是可以通过一个 api, 单次调用获得 一个用户的 信用卡过期时间 .
现在要求 在用户信息用卡过期的前三天,给用户发送邮件通知 .

请问如何避免每天大量全库用户调用 API 来实现这个功能 .

(信用卡过期时间 为  年月 eg: 07/21   2021年07月过期 ,  一般认为 当月的最后一天为过期时间)

**Comment by PuShaoWei** [comment]
收到，正在赶往现场

**Comment by m9rco** [comment]
### 0x01. 安全限制不能保存用户信用卡信息，不能保存信用卡过期时间
在这里**过期时间** 是一定的，用户信用卡信息可以不保存，知道是哪一个用户就可以了 ，但是过期时间一定需要保存的把，哪怕是加密起来？

### 0x02.  并且保证每天频繁全库调用`API`来实现
我认为最好的处理方式是在用户需要信用卡的逻辑处，加上过期时间，过期时间与单个用户需要绑定，可以用`RC4`与用户`ID`生成`Key`加密过期时间，库里是加密后的过期时间并与用户保持唯一，另外主要涉及的是`要求 在用户信息用卡过期的前三天,给用户发送邮件通知` ,于是乎，你是否存用户过期时间前三天的时间戳就可以了？？

**Comment by phpstudyone** [comment]
不,就是不能存储用户的任何信用卡信息 . 因为 PCI 标准认为,存储一个信息也是存,只要有存储用户信用卡行为,那么必须保证整个环境(服务器,数据库,防火墙巴拉巴拉的 全部都要符合一定级别的标准) .  但是我们无法保证符合这么多标准.所以 用户信用卡信息, 一律不能存储,只能调用.

**Comment by m9rco** [comment]
要求 
```
在用户信息用卡过期的前三天,给用户发送邮件通知 
```
于是乎，你是否存用户过期时间前三天的时间戳就可以了

**Comment by phpstudyone** [comment]
不行哇,死都不能存,不管啥形式的,不管加密还是什么的,,只要有办法推算出具体的过期时间,就不能存了.....

**Comment by m9rco** [comment]
```
提醒邮件 -> 获得过期时间 -> 调用API -> 全库用户调用 
```
> 解决问题避免全库调用API
1. 时间入库 （加密／解密／倒计时／天数值）

> 只要有办法推算出具体的过期时间,就不能存
1. 在你这里相当于用户关于信用卡的信息什么都没有
2. 你要获得只有去调用API          
3. 你是搞事的

**Comment by phpstudyone** [comment]
....   怎么可能是搞事呢,这是我遇到的真实问题.  近段时间就要求解决的. 哎😔

**Comment by m9rco** [comment]
那就感觉没办法了哦。。条件很单一嘛

**Comment by phpstudyone** [comment]
https://segmentfault.com/q/1010000011605992

**Comment by m9rco** [comment]
```
我们不存储过期时间，只存储先后顺序，比如用户A比用户B先过期，A就排B用户前面。实现方法很多，不再赘述；
```
确实没有推算具体时间， 这样排序后先查100 条记录 如果第100条就是明天的那就不往下了，确实是一种优化手段，惭愧，没有给你合理的解决方式
```
不行哇,死都不能存,不管啥形式的,不管加密还是什么的,,只要有办法推算出具体的过期时间,就不能存了.....
```
我看到这儿，我就不知道怎么弄了
