### ISSUE TITLE
寻找最长不含有重复字符的子串

### ISSUE THREAD

**Issue by icer-hyb** [m9rco/algorithm-php#55]
大佬这个算法有么？
例: 
abcabcbb->abc
bbbbb->b
wpwwkew->wke

**Comment by m9rco** [comment]
哈哈哈。。抱歉，能不能描述下 这是啥意思呀

**Comment by icer-hyb** [comment]
例：
abcdabcdefgh:
想要获取 efgh
abcd和abcd 长度和efgh一样,但是abcd出现了重复。所以获取结果应该是efgh

**Comment by pfinal-nc** [comment]
@yb19890724 是不是查找给定字符串在另外一个字符串中出现的次数?

**Comment by icer-hyb** [comment]
@Neroxiezi 
就在给定的字符串里面去匹配， 不是把给定的字符串放到另一个里面去匹配次数。
