### ISSUE TITLE
二分叉递归查找有个问题

### ISSUE THREAD

**Issue by jianyan74** [m9rco/algorithm-php#61]
php 里面 0== 'default' 是 true 导致了执行到$top=0的时候重新赋值$top=10 死循环了

改成下面的方式

        if (!is_numeric($top) && $top == 'default')
        {
            $top = count($container);
        }

**Comment by jianyan74** [comment]
或者
  $top === 'default' && $top = count($container);

**Comment by m9rco** [comment]
嗯嗯  看到了，当时测试的时候没有想到这个，谢谢拉～

**Comment by m9rco** [comment]
最近懒了，好久没写这个了，欢迎一起学习分享 😂
