### ISSUE TITLE
求问如何排序两个无序数组？？？？

### ISSUE THREAD

**Issue by Zhucola** [m9rco/algorithm-php#63]
您好，求问如何排序两个无序数组？？？？

我现在的解题思路就是先将两个数组合并成一个，然后再归并，但是我感觉不太好

**Comment by m9rco** [comment]
好问题！

在不要求空间复杂度的情况下，合并后在快排就好了

空间复杂度无上限的话，我感觉理论上是开线程或协程共同去排序，然后使用堆排序加归并排序，emmmm

**Comment by m9rco** [comment]
仔细想想  我好久没更新了，真是惭愧
